# Generated by Django 6.1.2 on 2026-10-07 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection_date', models.DateField()),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('SUBMITTED', 'Submitted'), ('RECONCILED', 'Reconciled'), ('REJECTED', 'Rejected')], default='COLLECTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', to='customers.customer')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', to='loans.repaymentschedule')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', to='loans.loan')),
            ],
        ),
    ]
