# Generated by Django 6.1.2 on 2026-10-08 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_collections', '0001_initial'),
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcollection',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='reconciliation.cashsubmission'),
        ),
    ]
