# Generated by Django 6.1.2 on 2026-10-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_date', models.DateField()),
                ('bank_reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DEPOSITED', 'Deposited'), ('SETTLED', 'Settled'), ('FAILED', 'Failed'), ('MISMATCH', 'Mismatch')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_deposits', to='branches.branch')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_deposits', to='reconciliation.reconciliation')),
            ],
        ),
    ]
